name: hayworkflow
on: 
  workflow_dispatch:
   inputs:
     environments:
       default: dev
       description: select the  environment 
       required: true
       type: choice
       options:
          - dev
          - prod
          - staging
       
jobs:
  code:
   runs-on: ubuntu-latest
   steps:
     - name : coding
       run: echo "coding in  progress "
  build:
   needs: code
   runs-on: ubuntu-latest
   steps:
     - name : coding
       run: echo "coding in  progress "
  test:
   needs: build
   runs-on: ubuntu-latest
   steps:
     - name : coding
       run: echo "coding in  progress "
  deploy:
   if: inputs.environments == 'dev'
   needs:  test
   runs-on: ubuntu-latest
   steps:
     - name : coding
       run: echo "coding in  progress "
  
