name: hellobuddy
on: 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: greet everyone
        run: echo "hay buddy how are you "
      - name: greet user
        run: echo "hay $USER "
